apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-microservice
  labels:
    app: notifications-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-microservice
  template:
    metadata:
      labels:
        app: notifications-microservice
    spec:
      containers:
        - name: notifications-microservice
          image: juanhoyos/microservice:notifications-v7
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: url
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsAccessKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsSecretKey
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsRegion
            - name: AWS_SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsSqsQueueUrlOrders
            - name: AWS_SNS_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsSnsTopicArnOrders
            - name: AWS_SQS_QUEUE_URL_PUBLISHER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: awsSqsQueueUrlPublisherNotifications
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"